-- Criando a sequência para a tabela T_USUARIO
CREATE SEQUENCE SEQ_T_USUARIO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Criando a tabela T_USUARIO
CREATE TABLE T_USUARIO (
    ID_USUARIO INTEGER DEFAULT SEQ_T_USUARIO.NEXTVAL NOT NULL,  -- Define o valor padrão usando a sequência
    NM_USUARIO VARCHAR2(100) NOT NULL,
    DS_EMAIL VARCHAR2(100) NOT NULL,
    DS_CONTAS VARCHAR2(2000),
    DS_SENHA VARCHAR2(100) NOT NULL,
    PF_COR VARCHAR2(200),
    PF_TEMA NUMBER(1) DEFAULT 0,
    ROLE VARCHAR2(50) DEFAULT 'USER',
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)  -- Definindo a chave primária
);
