CREATE SEQUENCE SEQ_T_USUARIO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE T_USUARIO (
    ID_USUARIO INTEGER NOT NULL,
    NM_USUARIO VARCHAR2(100) NOT NULL,
    DS_EMAIL VARCHAR2(100) NOT NULL,
    DS_SENHA VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(50) DEFAULT 'USER'
);

ALTER TABLE T_USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO);
