-- Criando a sequência para a tabela tb_email
CREATE SEQUENCE SEQ_T_EMAIL
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Criando a tabela tb_email
CREATE TABLE TBL_EMAIL (
    ID_EMAIL INTEGER DEFAULT SEQ_T_EMAIL.NEXTVAL NOT NULL PRIMARY KEY,
    DE_EMAIL VARCHAR2(255) NOT NULL,
    PARA_EMAIL VARCHAR2(255) NOT NULL,
    ASSUNTO VARCHAR2(255),
    CORPO VARCHAR2(4000),
    -- CORPO STRING,  -- Armazenar o corpo do e-mail como HTML
    DT_EMAIL DATE,
    SPAM NUMBER(1) DEFAULT 0  -- 0 para não spam, 1 para spam
    --CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USER(ID_USUARIO)
);