-- Criando a sequência para a tabela tb_email
CREATE SEQUENCE SEQ_T_EMAIL
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Criando a tabela tb_email
CREATE TABLE T_EMAIL (
    ID_EMAIL INTEGER DEFAULT SEQ_T_EMAIL.NEXTVAL NOT NULL PRIMARY KEY,
    ID_USUARIO INTEGER,
    DE_EMAIL VARCHAR2(255) NOT NULL,
    PARA_EMAIL VARCHAR2(255) NOT NULL,
    ASSUNTO VARCHAR2(255),
    -- CORPO STRING,  -- Armazenar o corpo do e-mail como HTML
    DT_EMAIL DATE,
    SPAM NUMBER(1) DEFAULT 0,  -- 0 para não spam, 1 para spam
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO(ID_USUARIO)
);
