-- Criando a sequência para a tabela T_EVENTO
CREATE SEQUENCE SEQ_T_EVENTO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


-- Criando a tabela T_EVENTO com nomes de restrição diferentes
CREATE TABLE T_EVENTO (
    ID_EVENTO INTEGER DEFAULT SEQ_T_EVENTO.NEXTVAL NOT NULL PRIMARY KEY,
    ID_USUARIO INTEGER NOT NULL,
    ID_EMAIL INTEGER NOT NULL,
    TITULO VARCHAR2(255) NOT NULL,
    DT_INICIAL DATE NOT NULL,
    HR_INICIAL TIMESTAMP NOT NULL,
    DT_FINAL DATE NOT NULL,
    HR_FINAL TIMESTAMP NOT NULL,
    LOCALIZACAO VARCHAR2(255) NOT NULL,
    CONSTRAINT FK_USUARIO_T_EVENTO FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO(ID_USUARIO),
    CONSTRAINT FK_EMAIL_T_EVENTO FOREIGN KEY (ID_EMAIL) REFERENCES T_EMAIL(ID_EMAIL)
);
