-- Criando a sequência para a tabela T_EVENTO
CREATE SEQUENCE SEQ_T_EVENTO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


-- Criando a tabela T_EVENTO com nomes de restrição diferentes
CREATE TABLE TBL_EVENT (
    ID_EVENTO INTEGER DEFAULT SEQ_T_EVENTO.NEXTVAL NOT NULL PRIMARY KEY,
    ID_USUARIO INTEGER NOT NULL,
    TITULO VARCHAR2(255) NOT NULL,
    DT_INICIAL DATE NOT NULL,
    HR_INICIAL TIMESTAMP NOT NULL,
    DT_FINAL DATE NOT NULL,
    HR_FINAL TIMESTAMP NOT NULL,
    LOCALIZACAO VARCHAR2(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    CONSTRAINT FK_USUARIO_TBL_EVENT FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USER(ID_USUARIO)
);